build:
  version: "1.0"

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
      
